stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 111.230.252.214:8085/app-service/rancher-deploy-demo-:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 111.230.252.214:8085
  when:
    branch:
      include:
      - master
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy-develop.yaml
  when:
    branch:
      include:
      - master
timeout: 60
notification: {}
